"""Initial migration

Revision ID: 96de52542f8a
Revises: 
Create Date: 2024-10-18 12:15:45.920058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96de52542f8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mobile_carriers',
    sa.Column('name', sa.Enum('ORANGE', 'MAROC_TELECOM', 'INWI', name='carriername'), nullable=False),
    sa.Column('profit_percentage', sa.Enum('ORANGE', 'MAROC_TELECOM', 'INWI', name='profitpercentage'), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('client_numbers',
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('mobile_carrier', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mobile_carrier'], ['mobile_carriers.name'], ),
    sa.PrimaryKeyConstraint('number')
    )
    with op.batch_alter_table('client_numbers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_numbers_timestamp'), ['timestamp'], unique=False)

    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('mobile_carrier', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['mobile_carrier'], ['mobile_carriers.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offers')
    with op.batch_alter_table('client_numbers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_numbers_timestamp'))

    op.drop_table('client_numbers')
    op.drop_table('users')
    op.drop_table('mobile_carriers')
    # ### end Alembic commands ###
